name: Update ECS Service
on:
  workflow_run:
    workflows: ["Build and push image to AWS ECR Repo"]
    types:
      - completed
jobs:
  Update:
    name: Update ECS Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ secrets.ECR_CLUSTER }} --service ${{ secrets.ECR_SERVICE }} --force-new-deployment
