name: Update ECS Service
on:
  workflow_run:
    workflows: ["Build and push image to AWS ECR Repo"]
    types:
      - completed
jobs:
  Update:
    name: Update ECS Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Update ECS Service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        id: update-ecs-service
        with:
          task-definition: task-definition.json
          service: ecrecsdemoservice4
          cluster: ecrecsdemo
          wait-for-service-stability: true
